# Generated by Django 4.1.3 on 2022-11-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["summ", "-time_create"]},
        ),
    ]
