# Generated by Django 4.1.3 on 2022-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="summ",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Ваш баланс"
            ),
        ),
    ]
