# Generated by Django 4.1.3 on 2022-11-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_balance_summ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="payments.transaction",
            ),
        ),
    ]
