# Generated by Django 4.1.3 on 2022-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["time_create"]},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="organization",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Организация"
            ),
        ),
    ]
